version: '3.9'

services:

  postgres:
    image: postgres:12.4-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    image: ${DOCKERHUB_USERNAME}/todolist:latest
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python3 manage.py runserver 0.0.0.0:8000
    expose:
      - 8000

  migrations:
    image: ${DOCKERHUB_USERNAME}/todolist:latest
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate
    volumes:
      - ./.env:/code/.env

  bot:
    image: ${DOCKERHUB_USERNAME}/todolist:latest
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python3 manage.py runbot

  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pg_data:

